version: '3.5'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - database:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  wordpress:
    depends_on:
      - db
    image: wordpress:latest  
    build: .
    restart: always
    ports:
      - 8030:80
    env_file:
      - .env
    environment:  
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes: 
      - ./src:/var/www/html/    

networks:
  back:

volumes:
  database: